name: FlutterNews
description: Aplikácia ktorá Vám poskytne čerstvé informácie zo života farnosti Veľký Šariš.

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^5.0.4
  rflutter_alert: ^1.0.3
  flutter_localizations:
    sdk: flutter

  url_launcher: ^5.4.1
  share: ^0.6.0+1
  http: ^0.12.0
  bsev: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
      - assets/place_holder.jpg
      - assets/place_holder_2.jpg
      - assets/place_holder_3.jpg
      - assets/flutterlogo.jpg
      - assets/applogo.png
      - resources/lang/en.json
      - resources/lang/pt.json
      - resources/lang/sk.json
